baseURL = 'https://blog.mfrazi.me/'
enableRobotsTXT = true
languageCode = 'en-us'
title = 'Personal Blog'
theme = 'PaperMod'

[params.assets]
  favicon = "https://assets.mfrazi.me/65540fc0-422d-4991-bc46-ef451157d0ef/db59e041-6fbf-4bd8-a5dc-e5fc7f236d11.png"
  favicon32x32 = "https://assets.mfrazi.me/65540fc0-422d-4991-bc46-ef451157d0ef/0ee8cd1a-0515-48e3-b03c-91a02b075e05.png"
  favicon16x16 = "https://assets.mfrazi.me/65540fc0-422d-4991-bc46-ef451157d0ef/5771d9ab-e561-4ff1-975d-21b67400dcd9.png"

[services]
  [services.googleAnalytics]
    id = 'G-HV7RHZJ57F'